# Pandas

## **Series**


**pd.Series([val1,val2,val3...],name="seriesname",index=[index1,index2...])**

In [3]:
import pandas as pd

In [4]:
age = pd.Series([10,20,30],name="age")
print(age)
print("age at index 2: ",age[2])

0    10
1    20
2    30
Name: age, dtype: int64
age at index 2:  30

In [5]:
print("age"[0])  # string accessing

a

In [6]:
marks = pd.Series([90,40,50,95],index=['Ganesh','suresh','ramesh','manish'])
print(marks)

Ganesh    90
suresh    40
ramesh    50
manish    95
dtype: int64

In [7]:
print(marks['manish'])

95

In [8]:
Score = pd.Series([90,40,50,95],name="marks", index=['Ganesh','suresh','ramesh','manish'])
print("Marks of ganesh: ",marks['Ganesh'])

Marks of ganesh:  90

# slicing on pandas

syntax

**var[starting_value:ending_value:updation]**

In [9]:
marks =pd.Series([110,120,130,140],name='Marks')
marks

0    110
1    120
2    130
3    140
Name: Marks, dtype: int64

In [10]:
print(marks[0:4])
print(marks[::2])
print(marks[1::2])
print(marks[2:8])

0    110
1    120
2    130
3    140
Name: Marks, dtype: int64
0    110
2    130
Name: Marks, dtype: int64
1    120
3    140
Name: Marks, dtype: int64
2    130
3    140
Name: Marks, dtype: int64

# filtering on series

syntax

**var[condition]**

In [11]:
sal=pd.Series([10000,35000,65000,55000,45000,40000],name='salary')
sal

0    10000
1    35000
2    65000
3    55000
4    45000
5    40000
Name: salary, dtype: int64

In [12]:
print(sal[sal<=50000])
print(sal[sal>10000])
print(sal[sal!=45000])

0    10000
1    35000
4    45000
5    40000
Name: salary, dtype: int64
1    35000
2    65000
3    55000
4    45000
5    40000
Name: salary, dtype: int64
0    10000
1    35000
2    65000
3    55000
5    40000
Name: salary, dtype: int64

# 2 rules for multiple conditions 

**1. () for each and every conditions**

**2.  & for and ,| for or**

In [13]:
sal

0    10000
1    35000
2    65000
3    55000
4    45000
5    40000
Name: salary, dtype: int64

In [14]:
print(sal[(sal>=55000) & (sal<=650000)])

2    65000
3    55000
Name: salary, dtype: int64

In [15]:
print(sal[(sal==55000) | (sal==65000)])

2    65000
3    55000
Name: salary, dtype: int64

# **DataFrame**

syntax

**variable_name={**

**"col_name1":[val1,val2,va3......],**

**"col_name2":[val1,val2,va3......],**

**"col_name3":[val1,val2,va3......],**

**"col_name4":[val1,val2,va3......],**

}**

**pd.DataFrame(variable)**

In [16]:
data={
    "name":['Revanth','Kumar','Bhanu'],
    "exp":[1,5,7],
    'salary':[100000,50000,800000]
}
df = pd.DataFrame(data)
df

      name  exp  salary
0  Revanth    1  100000
1    Kumar    5   50000
2    Bhanu    7  800000

In [17]:
print(df['name'])
df[df['salary']>50000]

0    Revanth
1      Kumar
2      Bhanu
Name: name, dtype: object

      name  exp  salary
0  Revanth    1  100000
2    Bhanu    7  800000

In [18]:
data={
    'movie_name':['winner','spidrman','kgf','salar'],
    'hero':['raj','kumar','ragu','ram'],
    'heroine':['has','kamala','charim','rashimika']
}
movies=pd.DataFrame(data)
print(movies)
print(movies[movies["hero"]=='ragu'])

  movie_name   hero    heroine
0     winner    raj        has
1   spidrman  kumar     kamala
2        kgf   ragu     charim
3      salar    ram  rashimika
  movie_name  hero heroine
2        kgf  ragu  charim

# operations on data frame

# indexing

# slicing

# filtering

# 1.indexing

**df[col_name][index]**

In [19]:
movies

  movie_name   hero    heroine
0     winner    raj        has
1   spidrman  kumar     kamala
2        kgf   ragu     charim
3      salar    ram  rashimika

In [20]:
movies["movie_name"]

0      winner
1    spidrman
2         kgf
3       salar
Name: movie_name, dtype: object

In [21]:
movies[["hero","heroine"]]

    hero    heroine
0    raj        has
1  kumar     kamala
2   ragu     charim
3    ram  rashimika

In [22]:
movies["hero"][0] # indexing

'raj'

# **slicing on data frame**

**var[si:ei:up]**

In [23]:
df=pd.DataFrame({
    'products':['laptop','mouse','keybord','monitor','headphones'],
    'quantity':[1,5,3,2,8],
    'price':[65000,700,2500,35000,12000]
})
df

     products  quantity  price
0      laptop         1  65000
1       mouse         5    700
2     keybord         3   2500
3     monitor         2  35000
4  headphones         8  12000

In [24]:
print(df[::2])

     products  quantity  price
0      laptop         1  65000
2     keybord         3   2500
4  headphones         8  12000

In [25]:
print(df[1:4])

  products  quantity  price
1    mouse         5    700
2  keybord         3   2500
3  monitor         2  35000

In [26]:
print(df[::-1])

     products  quantity  price
4  headphones         8  12000
3     monitor         2  35000
2     keybord         3   2500
1       mouse         5    700
0      laptop         1  65000

# **loc**

syntax

**df.loc[si:ei:up,['col1',col2','col3'.....]]**

ending index is inclusive in loc




**loc is a Pandas label-based indexing method.**

**It is used to access rows and columns using their labels/names.**

syntax 2

**df.loc[row_label, column_label]**

In [27]:
df

     products  quantity  price
0      laptop         1  65000
1       mouse         5    700
2     keybord         3   2500
3     monitor         2  35000
4  headphones         8  12000

In [28]:
print(df.loc[2]) #Select one row
print(df.loc[2, "quantity"]) #Select one column from a specific row
print(df.loc[:, ["quantity", "price"]]) #Select multiple columns
print(df.loc[[0, 2], ["quantity", "price"]]) #Select rows + columns
print(df.loc[df["quantity"] > 5]) #filtering with loc :========= df.loc[condition, columns]
print(df.loc[df["quantity"] > 5, ["products", "price"]]) #only particular columns
df.loc[4,"quantity"]=10  # modifying the data 
print(df.loc[4,"quantity"])
df.loc[df["quantity"] < 2, "quantity"] = 5 # modify multiple rows -- make quantity as 5 wher quantity less than 2

products    keybord
quantity          3
price          2500
Name: 2, dtype: object
3
   quantity  price
0         1  65000
1         5    700
2         3   2500
3         2  35000
4         8  12000
   quantity  price
0         1  65000
2         3   2500
     products  quantity  price
4  headphones         8  12000
     products  price
4  headphones  12000
10

In [29]:
df.loc[0:1,['products','quantity']]

  products  quantity
0   laptop         5
1    mouse         5

# **iloc**

syntax

**variable_name.iloc[row_slice,col_slice]**

**iloc means integer-location based indexing.**

**It is used to access DataFrame data using integer positions.**

In [30]:
d={
    "movies_name":['toxic','mizapur','kgf','spiderman','kantara','ghilli'],
    'hero_names':['yash','kahlin bhaia','yash','tom holland','rishib shetty','vijay'],
    'heroine':['kiara','bhumi','srinihi','zendaya','sapthami','trisha'],
    "movies_name1":['toxic','mizapur','kgf','spiderman','kantara','ghilli'],
    'hero_names1':['yash','kahlin bhaia','yash','tom holland','rishib shetty','vijay'],
    'heroine1':['kiara','bhumi','srinihi','zendaya','sapthami','trisha'],
    "movies_name2":['toxic','mizapur','kgf','spiderman','kantara','ghilli'],
    'hero_names2':['yash','kahlin bhaia','yash','tom holland','rishib shetty','vijay'],
    'heroine2':['kiara','bhumi','srinihi','zendaya','sapthami','trisha']
}
movies=pd.DataFrame(d)
movies

,movies_name,hero_names,heroine,movies_name1,hero_names1,heroine1,movies_name2,hero_names2,heroine2
0,toxic,yash,kiara,toxic,yash,kiara,toxic,yash,kiara
1,mizapur,kahlin bhaia,bhumi,mizapur,kahlin bhaia,bhumi,mizapur,kahlin bhaia,bhumi
2,kgf,yash,srinihi,kgf,yash,srinihi,kgf,yash,srinihi
3,spiderman,tom holland,zendaya,spiderman,tom holland,zendaya,spiderman,tom holland,zendaya
4,kantara,rishib shetty,sapthami,kantara,rishib shetty,sapthami,kantara,rishib shetty,sapthami
5,ghilli,vijay,trisha,ghilli,vijay,trisha,ghilli,vijay,trisha

In [31]:
movies.iloc[0:4,0:6]

  movies_name    hero_names  heroine movies_name1   hero_names1 heroine1
0       toxic          yash    kiara        toxic          yash    kiara
1     mizapur  kahlin bhaia    bhumi      mizapur  kahlin bhaia    bhumi
2         kgf          yash  srinihi          kgf          yash  srinihi
3   spiderman   tom holland  zendaya    spiderman   tom holland  zendaya

In [32]:
movies.iloc[::2,::2]

  movies_name   heroine    hero_names1 movies_name2  heroine2
0       toxic     kiara           yash        toxic     kiara
2         kgf   srinihi           yash          kgf   srinihi
4     kantara  sapthami  rishib shetty      kantara  sapthami

In [33]:
print("=======select one row======")
print(movies.iloc[2]) 

print("=========one cell=========")
print(movies.iloc[2,0]) 

print("=========select multiple rows=========")
print(movies.iloc[[0,2]])

print("=============Select multiple columns=========")
print("============select all rows , only columns at 1 and 3=============")
print(movies.iloc[:,[1,3]])

print("=================select all rows , select columns from 1 to 3(columns 1 and 2)")
print(movies.iloc[:,1:3])

=======select one row======
movies_name         kgf
hero_names         yash
heroine         srinihi
movies_name1        kgf
hero_names1        yash
heroine1        srinihi
movies_name2        kgf
hero_names2        yash
heroine2        srinihi
Name: 2, dtype: object
=========one cell=========
kgf
=========select multiple rows=========
  movies_name hero_names  heroine movies_name1 hero_names1 heroine1  \
0       toxic       yash    kiara        toxic        yash    kiara
2         kgf       yash  srinihi          kgf        yash  srinihi

  movies_name2 hero_names2 heroine2
0        toxic        yash    kiara
2          kgf        yash  srinihi
=============Select multiple columns=========
============select all rows , only columns at 1 and 3=============
      hero_names movies_name1
0           yash        toxic
1   kahlin bhaia      mizapur
2           yash          kgf
3    tom holland    spiderman
4  rishib shetty      kantara
5          vijay       ghilli
=================select all rows , select columns from 1 to 3(columns 1 and 2)
      hero_names   heroine
0           yash     kiara
1   kahlin bhaia     bhumi
2           yash   srinihi
3    tom holland   zendaya
4  rishib shetty  sapthami
5          vijay    trisha

In [34]:
print(movies.iloc[:,[1,3]])

print(movies.iloc[:,1:3])

      hero_names movies_name1
0           yash        toxic
1   kahlin bhaia      mizapur
2           yash          kgf
3    tom holland    spiderman
4  rishib shetty      kantara
5          vijay       ghilli
      hero_names   heroine
0           yash     kiara
1   kahlin bhaia     bhumi
2           yash   srinihi
3    tom holland   zendaya
4  rishib shetty  sapthami
5          vijay    trisha

# filtering on data frame

syntax

**variable_name[condition]**

In [35]:
df=pd.DataFrame({
    'name':['ram','lilly','raj','sham','luca'],
    'disease':['fever','cancer','sugar','bp','covid'],
    'age':[25,56,76,45,23],
    "bill":[2000,100000,4000,3000,50000]

})

In [36]:
df

    name disease  age    bill
0    ram   fever   25    2000
1  lilly  cancer   56  100000
2    raj   sugar   76    4000
3   sham      bp   45    3000
4   luca   covid   23   50000

In [37]:
df[df["bill"]>4000]

    name disease  age    bill
1  lilly  cancer   56  100000
4   luca   covid   23   50000

In [38]:
df[df["age"]<50]

   name disease  age   bill
0   ram   fever   25   2000
3  sham      bp   45   3000
4  luca   covid   23  50000

In [39]:
df[df["disease"]=="cancer"]

    name disease  age    bill
1  lilly  cancer   56  100000

In [40]:
df[(df['age']>30) & (df['disease']=='sugar')]

  name disease  age  bill
2  raj   sugar   76  4000

# **to create series using numpy and pandas**

In [41]:

import numpy as np

In [42]:
emp_id=np.arange(101,201)
pd.Series(emp_id,name='employee_id')

0     101
1     102
2     103
3     104
4     105
     ...
95    196
96    197
97    198
98    199
99    200
Name: employee_id, Length: 100, dtype: int64

# **to create dataframe using numpy and pandas**

In [43]:
emp_id = np.arange(101,201)
sal =np.random.randint(20000,80000,100)
age=np.random.randint(21,51,100)
bonus = np.ones(100,dtype=int)
df = pd.DataFrame({
    'employee_id':emp_id,
    'salary':sal,
    'age':age,
    'bonus':bonus
})
df

    employee_id  salary  age  bonus
0           101   68305   43      1
1           102   70532   48      1
2           103   32683   28      1
3           104   51567   22      1
4           105   69751   41      1
..          ...     ...  ...    ...
95          196   59459   50      1
96          197   66157   41      1
97          198   41232   32      1
98          199   59755   29      1
99          200   34537   33      1

[100 rows x 4 columns]

# **Converting CSV,Excel,JSON into DataFrame**

In [44]:
df = pd.read_csv("data/flipkart_sales.csv")
df.head()

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1

In [45]:
df=pd.read_excel('data/population.xlsx')
df.tail()

,LocID,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
45971,308.0,Grenada,2040.0,100+,100.0,-1.0,0.001,0.004,0.005
45972,426.0,Lesotho,2040.0,100+,100.0,-1.0,0.001,0.009,0.010
45973,516.0,Namibia,2040.0,100+,100.0,-1.0,0.001,0.003,0.004
45974,690.0,Seychelles,2040.0,100+,100.0,-1.0,0.001,0.007,0.008
45975,776.0,Tonga,2040.0,100+,100.0,-1.0,0.001,0.000,0.001

# **JSON**

In [46]:
import pandas as pd
data=pd.read_json('data/colors.json')
df=pd.json_normalize(data["colors"])
df.head()

    name      hex category  rgb.r  rgb.g  rgb.b
0  Black  #000000  neutral      0      0      0
1  White  #FFFFFF  neutral    255    255    255
2    Red  #FF0000  primary    255      0      0
3  Green  #00FF00  primary      0    255      0
4   Blue  #0000FF  primary      0      0    255

# **pandas built in methods to perform data exploration**

# **head()**

syntax

**variablename.head()**

**variablename.head(n)**

In [47]:
df.head()

    name      hex category  rgb.r  rgb.g  rgb.b
0  Black  #000000  neutral      0      0      0
1  White  #FFFFFF  neutral    255    255    255
2    Red  #FF0000  primary    255      0      0
3  Green  #00FF00  primary      0    255      0
4   Blue  #0000FF  primary      0      0    255

In [48]:
df.head(2)

    name      hex category  rgb.r  rgb.g  rgb.b
0  Black  #000000  neutral      0      0      0
1  White  #FFFFFF  neutral    255    255    255

# **tail()**


**variablename.tail()--->bottom 5 rows**


**variablename.tail(n)---> bottom n rows**

In [49]:
df.tail()

        name      hex category  rgb.r  rgb.g  rgb.b
30     Beige  #F5F5DC  neutral    245    245    220
31  Lavender  #E6E6FA     cool    230    230    250
32      Mint  #98FF98   nature    152    255    152
33     Peach  #FFCBA4     warm    255    203    164
34     Slate  #708090  neutral    112    128    144

In [50]:
df.tail(3)

     name      hex category  rgb.r  rgb.g  rgb.b
32   Mint  #98FF98   nature    152    255    152
33  Peach  #FFCBA4     warm    255    203    164
34  Slate  #708090  neutral    112    128    144

# **info()**

syntax

**variable_name.info()**

**used to understand the structure and quality of a dataset.**

shows information such as:
- Number of rows
- Number of columns
- Column names
- Non-null values
- Data types
- Memory usage

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      35 non-null     object
 1   hex       35 non-null     object
 2   category  35 non-null     object
 3   rgb.r     35 non-null     int64
 4   rgb.g     35 non-null     int64
 5   rgb.b     35 non-null     int64
dtypes: int64(3), object(3)
memory usage: 1.8+ KB

# **describe()**

**provides statistical summary information for numerical columns**

**works on numerical columns**

syntax

**variable_name.describe()-->numeric colum default**

**variabl_name.describe(include=object)-->for object val**

In [52]:
df.describe()

            rgb.r       rgb.g       rgb.b
count   35.000000   35.000000   35.000000
mean   157.600000  141.600000  131.114286
std    100.781126   97.005518   93.533816
min      0.000000    0.000000    0.000000
25%     69.500000   31.000000   46.000000
50%    192.000000  160.000000  130.000000
75%    255.000000  227.000000  214.500000
max    255.000000  255.000000  255.000000

In [53]:
df.head(3)

    name      hex category  rgb.r  rgb.g  rgb.b
0  Black  #000000  neutral      0      0      0
1  White  #FFFFFF  neutral    255    255    255
2    Red  #FF0000  primary    255      0      0

In [54]:
print("======summary of columns whose data type is object , doesn't include numerical columns======")
print(df.describe(include=object))

======summary of columns whose data type is object , doesn't include numerical columns======
         name      hex category
count      35       35       35
unique     35       35        7
top     Black  #000000  neutral
freq        1        1        7

In [55]:
print("++++========Include both NUMERICAL and CATEGORICAL/OBject  values===============")
print()
print(df.describe(include='all'))

++++========Include both NUMERICAL and CATEGORICAL/OBject  values===============

         name      hex category       rgb.r       rgb.g       rgb.b
count      35       35       35   35.000000   35.000000   35.000000
unique     35       35        7         NaN         NaN         NaN
top     Black  #000000  neutral         NaN         NaN         NaN
freq        1        1        7         NaN         NaN         NaN
mean      NaN      NaN      NaN  157.600000  141.600000  131.114286
std       NaN      NaN      NaN  100.781126   97.005518   93.533816
min       NaN      NaN      NaN    0.000000    0.000000    0.000000
25%       NaN      NaN      NaN   69.500000   31.000000   46.000000
50%       NaN      NaN      NaN  192.000000  160.000000  130.000000
75%       NaN      NaN      NaN  255.000000  227.000000  214.500000
max       NaN      NaN      NaN  255.000000  255.000000  255.000000

# **Column attribute**

syntax

**var.columns**

In [56]:
df.columns

Index(['name', 'hex', 'category', 'rgb.r', 'rgb.g', 'rgb.b'], dtype='object')

In [57]:
df["category"].dtype # pandas treat strings as objects

dtype('O')

# unique()

**gives the number of unique values.**

**columnName.unique()**

In [58]:
df['name'].unique()

array(['Black', 'White', 'Red', 'Green', 'Blue', 'Yellow', 'Cyan',
       'Magenta', 'Orange', 'Pink', 'Purple', 'Violet', 'Brown', 'Maroon',
       'Olive', 'Teal', 'Navy', 'Gray', 'Silver', 'Lime', 'Aqua', 'Coral',
       'Salmon', 'Khaki', 'Plum', 'Gold', 'Crimson', 'Indigo',
       'Turquoise', 'Ivory', 'Beige', 'Lavender', 'Mint', 'Peach',
       'Slate'], dtype=object)

# **value_counts()**

syntax

**var['col_name'].value_counts()**

**returns each unique value along with how many times it occurs.**

In [59]:
df['category'].value_counts()

category
neutral      7
cool         7
warm         7
earth        4
nature       4
secondary    3
primary      3
Name: count, dtype: int64

In [60]:
print(df['category'].unique())
print(df['category'].value_counts())

['neutral' 'primary' 'secondary' 'warm' 'cool' 'earth' 'nature']
category
neutral      7
cool         7
warm         7
earth        4
nature       4
secondary    3
primary      3
Name: count, dtype: int64

# **sort_values()**

syntax

**variable_name.sort_values(by='column_name')--->ascending order --------->>default** 

**variable_name.sort_values(by='column_name',ascending=False)--->descending**

In [61]:
df.sort_values(by='name' , ascending=True)

         name      hex   category  rgb.r  rgb.g  rgb.b
20       Aqua  #00CED1     nature      0    206    209
30      Beige  #F5F5DC    neutral    245    245    220
0       Black  #000000    neutral      0      0      0
4        Blue  #0000FF    primary      0      0    255
12      Brown  #A52A2A      earth    165     42     42
21      Coral  #FF7F50       warm    255    127     80
26    Crimson  #DC143C       warm    220     20     60
6        Cyan  #00FFFF  secondary      0    255    255
25       Gold  #FFD700       warm    255    215      0
17       Gray  #808080    neutral    128    128    128
3       Green  #00FF00    primary      0    255      0
27     Indigo  #4B0082       cool     75      0    130
29      Ivory  #FFFFF0    neutral    255    255    240
23      Khaki  #F0E68C      earth    240    230    140
31   Lavender  #E6E6FA       cool    230    230    250
19       Lime  #32CD32     nature     50    205     50
7     Magenta  #FF00FF  secondary    255      0    255
13     Maroon  #800000      earth    128      0      0
32       Mint  #98FF98     nature    152    255    152
16       Navy  #000080       cool      0      0    128
14      Olive  #808000      earth    128    128      0
8      Orange  #FFA500       warm    255    165      0
33      Peach  #FFCBA4       warm    255    203    164
9        Pink  #FFC0CB       warm    255    192    203
24       Plum  #DDA0DD       cool    221    160    221
10     Purple  #800080       cool    128      0    128
2         Red  #FF0000    primary    255      0      0
22     Salmon  #FA8072       warm    250    128    114
18     Silver  #C0C0C0    neutral    192    192    192
34      Slate  #708090    neutral    112    128    144
15       Teal  #008080       cool      0    128    128
28  Turquoise  #40E0D0     nature     64    224    208
11     Violet  #EE82EE       cool    238    130    238
1       White  #FFFFFF    neutral    255    255    255
5      Yellow  #FFFF00  secondary    255    255      0

# **sample()**

syntax

**variable_name.sample()-->random 1 record**

**variable_name.sample(n)-->random n records**

**sample() is random, while head() and tail() always select from the beginning/end.**

In [62]:
df.sample()

     name      hex category  rgb.r  rgb.g  rgb.b
8  Orange  #FFA500     warm    255    165      0

In [63]:
df.sample(2)

    name      hex category  rgb.r  rgb.g  rgb.b
3  Green  #00FF00  primary      0    255      0
9   Pink  #FFC0CB     warm    255    192    203

In [64]:
print("==================Returns 25% of the rows randomly================")
df.sample(frac=0.25) #frac=0.5

==================Returns 25% of the rows randomly================

        name      hex category  rgb.r  rgb.g  rgb.b
29     Ivory  #FFFFF0  neutral    255    255    240
27    Indigo  #4B0082     cool     75      0    130
18    Silver  #C0C0C0  neutral    192    192    192
19      Lime  #32CD32   nature     50    205     50
0      Black  #000000  neutral      0      0      0
33     Peach  #FFCBA4     warm    255    203    164
31  Lavender  #E6E6FA     cool    230    230    250
30     Beige  #F5F5DC  neutral    245    245    220
22    Salmon  #FA8072     warm    250    128    114

# **shape**

**variable_name.shape**

In [65]:
df.shape

(35, 6)

# **dtypes**

**variable_name.dtypes**

In [66]:
df.dtypes

name        object
hex         object
category    object
rgb.r        int64
rgb.g        int64
rgb.b        int64
dtype: object

In [67]:
df['name'].dtype

dtype('O')

# **checking missing values**

In [68]:
print(df.head().isnull())
print("================")
print(df.isnull().sum())
print("=========")
print(df['name'].isnull().sum())

    name    hex  category  rgb.r  rgb.g  rgb.b
0  False  False     False  False  False  False
1  False  False     False  False  False  False
2  False  False     False  False  False  False
3  False  False     False  False  False  False
4  False  False     False  False  False  False
================
name        0
hex         0
category    0
rgb.r       0
rgb.g       0
rgb.b       0
dtype: int64
=========
0

# **checking the duplicated rows**

In [69]:
print(df.head().duplicated())
print("===============")
print(df.duplicated().sum())

0    False
1    False
2    False
3    False
4    False
dtype: bool
===============
0

# **Data Cleaning**

In [70]:
df=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding="ISO-8859-1")
df.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

# **1.rename column name**

syntax

**var_name.rename(columns=s_var_name,inplace=True)**

**returns a new DataFrame and does not modify the original df**

**inplace=True it will make changes in orginal data frame**

In [71]:
df.columns

Index(['ano', 'mes', 'estado', 'numero', 'encontro'], dtype='object')

In [72]:
d={
    'ano':'year','mes':'month','estado':'state','numero':'no-of-fires','encontro':'date'
}

df.rename(columns=d,inplace=True)
df.head()

   year    month state no-of-fires      date
0  1998  Janeiro  Acre     0 Fires  1/1/1998
1  1999  Janeiro  Acre     0 Fires  1/1/1999
2  2000  Janeiro  Acre     0 Fires  1/1/2000
3  2001  Janeiro  Acre     0 Fires  1/1/2001
4  2002  Janeiro  Acre     0 Fires  1/1/2002

In [73]:
# df.rename(columns={'Year':'year'},inplace=True)
df.head()

   year    month state no-of-fires      date
0  1998  Janeiro  Acre     0 Fires  1/1/1998
1  1999  Janeiro  Acre     0 Fires  1/1/1999
2  2000  Janeiro  Acre     0 Fires  1/1/2000
3  2001  Janeiro  Acre     0 Fires  1/1/2001
4  2002  Janeiro  Acre     0 Fires  1/1/2002

# **2.drop duplicated rows**

syntax

**var_name.drop_duplicates(inplace=True)**

In [74]:
import pandas as pd

In [75]:
df.duplicated().sum()

np.int64(30)

In [76]:
df

      year     month      state no-of-fires      date
0     1998   Janeiro       Acre     0 Fires  1/1/1998
1     1999   Janeiro       Acre     0 Fires  1/1/1999
2     2000   Janeiro       Acre     0 Fires  1/1/2000
3     2001   Janeiro       Acre     0 Fires  1/1/2001
4     2002   Janeiro       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  Dezembro  Tocantins         128  1/1/2012
6450  2013  Dezembro  Tocantins          85  1/1/2013
6451  2014  Dezembro  Tocantins         223  1/1/2014
6452  2015  Dezembro  Tocantins         373  1/1/2015
6453  2016  Dezembro  Tocantins         119  1/1/2016

[6454 rows x 5 columns]

In [77]:
df.drop_duplicates(inplace=True)

In [78]:
df.duplicated().sum()

np.int64(0)

In [79]:
df['month'].unique()

array(['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

# **3.Changing the data in a column**

Syntax:

**df["col_name"]=df["col_name"].map(d)**

**map() is used to replace/transform values in a Pandas Series based on a mapping dictionary.**

In [80]:
d={ 'Janeiro':'jan', 'Fevereiro':'feb', 'Março':'mar', 'Abril':'apr', 'Maio':'may', 'Junho':'jun', 'Julho':'jul',
    'Agosto':'aug', 'Setembro':'sep', 'Outubro':'oct', 'Novembro':'nov','Dezembro':'Dec'
}
df["month"]=df["month"].map(d)
df.head()

   year month state no-of-fires      date
0  1998   jan  Acre     0 Fires  1/1/1998
1  1999   jan  Acre     0 Fires  1/1/1999
2  2000   jan  Acre     0 Fires  1/1/2000
3  2001   jan  Acre     0 Fires  1/1/2001
4  2002   jan  Acre     0 Fires  1/1/2002

# **4.Removing unwanted data in a column**
Syntax:

**df["col_name"]=df["col_name"].str.strip("Unwanted data")**

In [81]:
df['no-of-fires'].unique()

array(['0 Fires', '10 Fires', '12 Fires', ..., '2.032', '833', '623'],
      shape=(1729,), dtype=object)

In [82]:
df['no-of-fires']=df['no-of-fires'].str.strip(' Fires')

In [83]:
df.head()

   year month state no-of-fires      date
0  1998   jan  Acre           0  1/1/1998
1  1999   jan  Acre           0  1/1/1999
2  2000   jan  Acre           0  1/1/2000
3  2001   jan  Acre           0  1/1/2001
4  2002   jan  Acre           0  1/1/2002

# **5.Changing the data type of a column**

Syntax:

**df["col_name"]=df["col_name"].astype(destination type)**

In [84]:
df['no-of-fires']=df['no-of-fires'].astype(float)
df.head()

   year month state  no-of-fires      date
0  1998   jan  Acre          0.0  1/1/1998
1  1999   jan  Acre          0.0  1/1/1999
2  2000   jan  Acre          0.0  1/1/2000
3  2001   jan  Acre          0.0  1/1/2001
4  2002   jan  Acre          0.0  1/1/2002

In [89]:
df['no-of-fires'].unique()
df.sample(5)

      year month        state  no-of-fires      date
928   2008   nov     Amazonas       39.000  1/1/2008
4909  2006   jul          Rio       45.000  1/1/2006
1166  2007   nov        Bahia        2.126  1/1/2007
2608  2015   nov  Mato Grosso        1.930  1/1/2015
753   2013   feb     Amazonas       16.000  1/1/2013

In [90]:
df['month'].unique()

array(['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep',
       'oct', 'nov', 'Dec'], dtype=object)

In [91]:
df1=pd.DataFrame({
    "Stu_id":[101,102,103,104,105],
    "Branch":[np.nan,"Pune","kochi",np.nan,"Pune"],
    "Marks":[100,np.nan,np.nan,45,63]
})
df1

   Stu_id Branch  Marks
0     101    NaN  100.0
1     102   Pune    NaN
2     103  kochi    NaN
3     104    NaN   45.0
4     105   Pune   63.0

# **7.Handling missing values**

Syntax:

**df.dropna(inplace=True)**

**Remove rows that contain missing values and directly update the original DataFrame.**

In [92]:
df1.dropna(inplace=True)
df1

   Stu_id Branch  Marks
4     105   Pune   63.0

In [93]:
df1=pd.DataFrame({
    "Stu_id":[101,102,103,104,105],
    "Branch":[np.nan,"Pune","kochi",np.nan,"Pune"],
    "Marks":[100,np.nan,np.nan,45,63]
})
df1

   Stu_id Branch  Marks
0     101    NaN  100.0
1     102   Pune    NaN
2     103  kochi    NaN
3     104    NaN   45.0
4     105   Pune   63.0

# **for numeric**

Syntax:

**df["col_name"]=df["col_name"].fillna(df["col_name"].mean())**

In [95]:
df1['Marks'] = df1['Marks'].fillna(df1['Marks'].mean())
df1.head()

   Stu_id Branch       Marks
0     101    NaN  100.000000
1     102   Pune   69.333333
2     103  kochi   69.333333
3     104    NaN   45.000000
4     105   Pune   63.000000

In [96]:
df1["Marks"]=df1["Marks"].astype(int)
df1.head()

   Stu_id Branch  Marks
0     101    NaN    100
1     102   Pune     69
2     103  kochi     69
3     104    NaN     45
4     105   Pune     63

In [97]:
df1["Branch"].value_counts()

Branch
Pune     2
kochi    1
Name: count, dtype: int64

# **for string**

Syntax:

**df["col_name"]=df["col_name"].fillna(freq_value)**

In [98]:
df1["Branch"]=df1["Branch"].fillna("Pune")
df1.head()

   Stu_id Branch  Marks
0     101   Pune    100
1     102   Pune     69
2     103  kochi     69
3     104   Pune     45
4     105   Pune     63

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         6424 non-null   int64
 1   month        6424 non-null   object
 2   state        6424 non-null   object
 3   no-of-fires  6292 non-null   float64
 4   date         6424 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 301.1+ KB

In [100]:
df["no-of-fires"].isnull().sum()

np.int64(132)

In [103]:
df['no-of-fires'].isnull().sum()

np.int64(132)

In [106]:
df["no-of-fires"]=df["no-of-fires"].fillna(df["no-of-fires"].mean())
df

      year month      state  no-of-fires      date
0     1998   jan       Acre          0.0  1/1/1998
1     1999   jan       Acre          0.0  1/1/1999
2     2000   jan       Acre          0.0  1/1/2000
3     2001   jan       Acre          0.0  1/1/2001
4     2002   jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6424 rows x 5 columns]

In [107]:
df["no-of-fires"].isnull().sum()

np.int64(0)

In [108]:
df["no-of-fires"]=df["no-of-fires"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         6424 non-null   int64
 1   month        6424 non-null   object
 2   state        6424 non-null   object
 3   no-of-fires  6424 non-null   int64
 4   date         6424 non-null   object
dtypes: int64(2), object(3)
memory usage: 301.1+ KB

# **8.rearranging the order of the columns**

syntax

**df=df[df.columns[new_orders]]**

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         6424 non-null   int64
 1   month        6424 non-null   object
 2   state        6424 non-null   object
 3   no-of-fires  6424 non-null   int64
 4   date         6424 non-null   object
dtypes: int64(2), object(3)
memory usage: 301.1+ KB

In [112]:
new_order=[4,1,2,3,0]
df=df[df.columns[new_order]]

In [113]:
df.head()

       date month state  no-of-fires  year
0  1/1/1998   jan  Acre            0  1998
1  1/1/1999   jan  Acre            0  1999
2  1/1/2000   jan  Acre            0  2000
3  1/1/2001   jan  Acre            0  2001
4  1/1/2002   jan  Acre            0  2002

# **9.drop unwanted columns**

syntax

**df=df.drop([col1,col2...coln],axis=1)**

**we can drop rows or columns based on the axis=0 or 1**

In [115]:
df = df.drop(['year'],axis=1)

In [ ]:
df.head()

       date month state  no-of-fires
0  1/1/1998   jan  Acre            0
1  1/1/1999   jan  Acre            0
2  1/1/2000   jan  Acre            0
3  1/1/2001   jan  Acre            0
4  1/1/2002   jan  Acre            0

In [117]:
df2=pd.DataFrame({
    'colors':['purple','pink','blue','red',np.nan,np.nan],
    'fruits':['apple','mango','kiwi','orange',np.nan,np.nan],
    'flowers':['lilly','rose','tulip','lotus',np.nan,np.nan],
    'sports':['cricket','tennies','vollyball','hocky',np.nan,np.nan]

})
df2

   colors  fruits flowers     sports
0  purple   apple   lilly    cricket
1    pink   mango    rose    tennies
2    blue    kiwi   tulip  vollyball
3     red  orange   lotus      hocky
4     NaN     NaN     NaN        NaN
5     NaN     NaN     NaN        NaN

# **10.drop unwanted rows**

syntax

**df=df.drop([index 1,index 2,...,index n])**

**by default axis=0**

In [118]:
df2=df2.drop([4,5])

In [119]:
df2.head()

   colors  fruits flowers     sports
0  purple   apple   lilly    cricket
1    pink   mango    rose    tennies
2    blue    kiwi   tulip  vollyball
3     red  orange   lotus      hocky

In [120]:
df.tail()

          date month      state  no-of-fires
6449  1/1/2012   Dec  Tocantins          128
6450  1/1/2013   Dec  Tocantins           85
6451  1/1/2014   Dec  Tocantins          223
6452  1/1/2015   Dec  Tocantins          373
6453  1/1/2016   Dec  Tocantins          119

In [123]:
#df=df.drop([6449,6450,6451,6452,6453])
df.tail()

          date month      state  no-of-fires
6444  1/1/2007   Dec  Tocantins           13
6445  1/1/2008   Dec  Tocantins            7
6446  1/1/2009   Dec  Tocantins           46
6447  1/1/2010   Dec  Tocantins           72
6448  1/1/2011   Dec  Tocantins          105

# **11.resetting index**

syntax

**df.reset_index(inplace=True)**

In [124]:
df.head()

       date month state  no-of-fires
0  1/1/1998   jan  Acre            0
1  1/1/1999   jan  Acre            0
2  1/1/2000   jan  Acre            0
3  1/1/2001   jan  Acre            0
4  1/1/2002   jan  Acre            0

In [127]:
df.reset_index(inplace=True)
df

      level_0  index      date month      state  no-of-fires
0           0      0  1/1/1998   jan       Acre            0
1           1      1  1/1/1999   jan       Acre            0
2           2      2  1/1/2000   jan       Acre            0
3           3      3  1/1/2001   jan       Acre            0
4           4      4  1/1/2002   jan       Acre            0
...       ...    ...       ...   ...        ...          ...
6414     6414   6444  1/1/2007   Dec  Tocantins           13
6415     6415   6445  1/1/2008   Dec  Tocantins            7
6416     6416   6446  1/1/2009   Dec  Tocantins           46
6417     6417   6447  1/1/2010   Dec  Tocantins           72
6418     6418   6448  1/1/2011   Dec  Tocantins          105

[6419 rows x 6 columns]

   index      date month state  no-of-fires
0      0  1/1/1998   jan  Acre            0
1      1  1/1/1999   jan  Acre            0
2      2  1/1/2000   jan  Acre            0
3      3  1/1/2001   jan  Acre            0
4      4  1/1/2002   jan  Acre            0

In [134]:
#df=df.drop(['index'],axis=1)
df=df.drop(['level_0'],axis=1)

In [135]:
df

          date month      state  no-of-fires
0     1/1/1998   jan       Acre            0
1     1/1/1999   jan       Acre            0
2     1/1/2000   jan       Acre            0
3     1/1/2001   jan       Acre            0
4     1/1/2002   jan       Acre            0
...        ...   ...        ...          ...
6414  1/1/2007   Dec  Tocantins           13
6415  1/1/2008   Dec  Tocantins            7
6416  1/1/2009   Dec  Tocantins           46
6417  1/1/2010   Dec  Tocantins           72
6418  1/1/2011   Dec  Tocantins          105

[6419 rows x 4 columns]

# **12.replace the value in a column**
syntax
### df['col_name']=df['col_name'].str.replace('old','new')

In [136]:
df['month'] = df['month'].replace('jan','january')
df

          date    month      state  no-of-fires
0     1/1/1998  january       Acre            0
1     1/1/1999  january       Acre            0
2     1/1/2000  january       Acre            0
3     1/1/2001  january       Acre            0
4     1/1/2002  january       Acre            0
...        ...      ...        ...          ...
6414  1/1/2007      Dec  Tocantins           13
6415  1/1/2008      Dec  Tocantins            7
6416  1/1/2009      Dec  Tocantins           46
6417  1/1/2010      Dec  Tocantins           72
6418  1/1/2011      Dec  Tocantins          105

[6419 rows x 4 columns]

# **13. setting a column as index**

syntax

**df.set_index('col_name',inplace=True)**

In [137]:
df.set_index('date',inplace=True)
df

            month      state  no-of-fires
date
1/1/1998  january       Acre            0
1/1/1999  january       Acre            0
1/1/2000  january       Acre            0
1/1/2001  january       Acre            0
1/1/2002  january       Acre            0
...           ...        ...          ...
1/1/2007      Dec  Tocantins           13
1/1/2008      Dec  Tocantins            7
1/1/2009      Dec  Tocantins           46
1/1/2010      Dec  Tocantins           72
1/1/2011      Dec  Tocantins          105

[6419 rows x 3 columns]

# **practice to clean data set**

In [139]:
df=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/laptopData.csv')
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [142]:
df=df.drop(['Unnamed: 0'],axis=1)
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [143]:
df.duplicated().sum()

np.int64(58)

In [144]:
df.columns

Index(['Company', 'TypeName', 'Inches', 'ScreenResolution', 'Cpu', 'Ram',
       'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='object')

In [145]:
df.drop_duplicates(inplace=True)

In [146]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [147]:
df.dropna(inplace= True)

In [148]:
df['Company'].unique()

array(['Apple', 'HP', 'Acer', 'Asus', 'Dell', 'Lenovo', 'Chuwi', 'MSI',
       'Microsoft', 'Toshiba', 'Huawei', 'Xiaomi', 'Vero', 'Razer',
       'Mediacom', 'Samsung', 'Google', 'Fujitsu', 'LG'], dtype=object)

In [149]:
df['TypeName'].unique()

array(['Ultrabook', 'Notebook', 'Gaming', '2 in 1 Convertible',
       'Workstation', 'Netbook'], dtype=object)

In [150]:
df['Inches'].unique()

array(['13.3', '15.6', '15.4', '14', '12', '17.3', '13.5', '12.5', '13',
       '18.4', '13.9', '11.6', '25.6', '35.6', '12.3', '27.3', '24',
       '33.5', '?', '31.6', '17', '15', '14.1', '11.3', '10.1'],
      dtype=object)

In [ ]:

df['Inches'] = df['Inches'].replace('?',np.nan)

In [154]:
df['Inches']=df['Inches'].astype(float)
df['Inches'] = df['Inches'].fillna(df['Inches'].mean())

In [155]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [156]:
df['Inches'].unique()

array([13.3      , 15.6      , 15.4      , 14.       , 12.       ,
       17.3      , 13.5      , 12.5      , 13.       , 18.4      ,
       13.9      , 11.6      , 25.6      , 35.6      , 12.3      ,
       27.3      , 24.       , 33.5      , 15.1388576, 31.6      ,
       17.       , 15.       , 14.1      , 11.3      , 10.1      ])

In [157]:
df['Ram'] =df['Ram'].str.strip('GB')

In [158]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [159]:
df['Ram'] = df['Ram'].astype(int)

In [160]:
df['Ram'].dtype

dtype('int64')

In [161]:
df['Memory'].value_counts()

Memory
256GB SSD                        401
1TB HDD                          209
500GB HDD                        121
512GB SSD                        112
128GB SSD +  1TB HDD              92
128GB SSD                         72
256GB SSD +  1TB HDD              71
32GB Flash Storage                35
2TB HDD                           16
512GB SSD +  1TB HDD              14
1TB SSD                           13
64GB Flash Storage                12
256GB SSD +  2TB HDD              10
256GB Flash Storage                8
16GB Flash Storage                 7
1.0TB Hybrid                       7
32GB SSD                           6
128GB Flash Storage                4
180GB SSD                          4
16GB SSD                           3
512GB SSD +  2TB HDD               3
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
1TB SSD +  1TB HDD                 2
512GB Flash Storage                2
512GB SSD +  512GB SSD             1
64GB SSD                           1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
512GB SSD +  256GB SSD             1
?                                  1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [163]:
df['Memory'] = df['Memory'].str.replace('?','256 SSD')

In [164]:

df['Weight']=df['Weight'].str.replace("kg","")
df['Weight']=df['Weight'].replace("?",np.nan)
df['Weight']=df['Weight'].astype(float)
df['Weight']=df['Weight'].fillna(df['Weight'].mean())

# **group by and aggregation**

syntax

**var=df.groupby("categoriacl col")**

**var.groups**

**var.get_groups("group_name")**

In [165]:
df=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv")

In [166]:
df.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [167]:
df['department'].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [ ]:
sal = df.groupby('salary')

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001C524DBEAD0>

In [172]:
dept = df.groupby('department')

In [173]:
print(sal.groups)
print(dept.groups)

{'high': [72, 111, 189, 267, 306, 345, 384, 423, 462, 501, 540, 579, 618, 657, 696, 735, 774, 813, 852, 891, 930, 969, 1008, 1047, 1086, 1125, 1164, 1203, 1242, 1281, 1320, 1359, 1398, 1437, 1476, 1515, 1554, 1593, 1632, 1671, 1710, 1749, 1788, 1827, 1866, 1905, 1944, 1983, 2022, 2061, 2100, 2139, 2178, 2217, 2256, 2295, 2334, 2373, 2412, 2451, 2490, 2529, 2568, 2607, 2646, 2685, 2724, 2763, 2802, 2841, 2880, 2919, 2958, 2997, 3036, 3075, 3114, 3153, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199, 3200, 3201, 3202, 3203, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238, 3270, 3289, ...], 'low': [0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 73, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 112, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, ...], 'medium': [1, 2, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 74, 75, 76, 77, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 113, 114, 115, 116, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 191, 192, 193, 194, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 269, 270, 271, 272, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 308, 309, 310, 311, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 347, 348, 349, 350, 372, 373, ...]}
{'IT': [61, 62, 63, 64, 65, 70, 138, 139, 140, 141, 142, 147, 214, 215, 216, 217, 218, 223, 291, 292, 293, 294, 295, 300, 367, 368, 369, 370, 371, 376, 443, 444, 445, 446, 447, 452, 519, 520, 521, 522, 523, 528, 595, 596, 597, 598, 599, 604, 671, 672, 673, 674, 675, 680, 747, 748, 749, 750, 751, 756, 823, 824, 825, 826, 827, 832, 899, 900, 901, 902, 903, 908, 975, 976, 977, 978, 979, 984, 1051, 1052, 1053, 1054, 1055, 1060, 1127, 1128, 1129, 1130, 1131, 1136, 1204, 1205, 1206, 1207, 1208, 1213, 1214, 1215, 1216, 1281, ...], 'RandD': [301, 302, 303, 304, 305, 453, 454, 455, 456, 457, 605, 606, 607, 608, 609, 833, 834, 835, 836, 837, 985, 986, 987, 988, 989, 1061, 1062, 1063, 1064, 1065, 1217, 1218, 1219, 1291, 1292, 1293, 1294, 1295, 1296, 1368, 1369, 1370, 1371, 1372, 1373, 1445, 1446, 1447, 1448, 1449, 1450, 1522, 1523, 1524, 1525, 1526, 1598, 1599, 1600, 1601, 1602, 1675, 1676, 1677, 1678, 1679, 1751, 1752, 1753, 1754, 1755, 1827, 1828, 1829, 1830, 1831, 1903, 1904, 1905, 1906, 1907, 1979, 1980, 1981, 1982, 1983, 2055, 2056, 2057, 2058, 2059, 2131, 2132, 2133, 2134, 2135, 2207, 2208, 2209, 2210, ...], 'accounting': [28, 29, 30, 79, 105, 106, 107, 155, 181, 182, 183, 224, 225, 232, 258, 259, 260, 308, 334, 335, 336, 377, 378, 384, 410, 411, 412, 460, 486, 487, 488, 529, 530, 536, 562, 563, 564, 612, 638, 639, 640, 688, 714, 715, 716, 764, 790, 791, 792, 840, 866, 867, 868, 916, 942, 943, 944, 992, 1018, 1019, 1020, 1068, 1094, 1095, 1096, 1145, 1171, 1172, 1173, 1222, 1248, 1249, 1250, 1299, 1325, 1326, 1327, 1376, 1402, 1403, 1404, 1453, 1479, 1480, 1481, 1529, 1555, 1556, 1557, 1606, 1632, 1633, 1634, 1682, 1708, 1709, 1710, 1758, 1784, 1785, ...], 'hr': [31, 32, 33, 34, 108, 109, 110, 111, 184, 185, 186, 187, 226, 227, 228, 261, 262, 263, 264, 337, 338, 339, 340, 379, 380, 381, 413, 414, 415, 416, 489, 490, 491, 492, 531, 532, 533, 565, 566, 567, 568, 641, 642, 643, 644, 717, 718, 719, 720, 793, 794, 795, 796, 869, 870, 871, 872, 945, 946, 947, 948, 1021, 1022, 1023, 1024, 1097, 1098, 1099, 1100, 1174, 1175, 1176, 1177, 1251, 1252, 1253, 1254, 1328, 1329, 1330, 1331, 1405, 1406, 1407, 1408, 1482, 1483, 1484, 1485, 1558, 1559, 1560, 1561, 1635, 1636, 1637, 1638, 1711, 1712, 1713, ...], 'management': [60, 82, 137, 158, 213, 235, 290, 311, 366, 387, 442, 463, 518, 539, 594, 615, 670, 691, 746, 767, 822, 843, 898, 919, 974, 995, 1050, 1071, 1126, 1148, 1203, 1225, 1280, 1302, 1357, 1379, 1434, 1456, 1511, 1532, 1587, 1609, 1664, 1685, 1740, 1761, 1816, 1837, 1892, 1913, 1968, 1989, 2044, 2065, 2120, 2141, 2196, 2217, 2272, 2293, 2348, 2369, 2424, 2445, 2500, 2522, 2577, 2599, 2654, 2676, 2731, 2753, 2808, 2830, 2885, 2906, 2961, 2983, 3038, 3059, 3114, 3135, 3190, 3211, 3266, 3287, 3342, 3363, 3418, 3439, 3494, 3515, 3570, 3591, 3646, 3667, 3722, 3743, 3798, 3819, ...], 'marketing': [77, 83, 84, 85, 148, 149, 150, 151, 152, 153, 159, 160, 161, 229, 230, 236, 237, 238, 306, 312, 313, 314, 382, 388, 389, 390, 458, 464, 465, 466, 534, 540, 541, 542, 610, 616, 617, 618, 686, 692, 693, 694, 762, 768, 769, 770, 838, 844, 845, 846, 914, 920, 921, 922, 990, 996, 997, 998, 1066, 1072, 1073, 1074, 1142, 1143, 1149, 1150, 1151, 1220, 1226, 1227, 1228, 1297, 1303, 1304, 1305, 1374, 1380, 1381, 1382, 1451, 1457, 1458, 1459, 1527, 1533, 1534, 1535, 1603, 1604, 1610, 1611, 1612, 1680, 1686, 1687, 1688, 1756, 1762, 1763, 1764, ...], 'product_mng': [66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 143, 144, 145, 146, 219, 220, 221, 222, 296, 297, 298, 299, 372, 373, 374, 375, 448, 449, 450, 451, 524, 525, 526, 527, 600, 601, 602, 603, 676, 677, 678, 679, 752, 753, 754, 755, 828, 829, 830, 831, 904, 905, 906, 907, 980, 981, 982, 983, 1056, 1057, 1058, 1059, 1132, 1133, 1134, 1135, 1209, 1210, 1211, 1212, 1286, 1287, 1288, 1289, 1363, 1364, 1365, 1366, 1440, 1441, 1442, 1443, 1517, 1518, 1519, 1520, 1593, 1594, 1595, 1596, 1670, 1671, 1672, 1673, 1746, 1747, 1748, 1749, 1822, 1823, ...], 'sales': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 78, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 154, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 231, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 307, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, ...], 'support': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 80, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 156, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 233, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 309, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 385, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 461, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 537, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 613, 656, 657, 658, 659, ...], 'technical': [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 57, 58, 59, 81, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 134, 135, 136, 157, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 210, 211, 212, 234, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 287, 288, 289, 310, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 363, 364, 365, 386, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 439, 440, 441, 462, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, ...]}

In [174]:
dept.get_group('sales')

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14967,87507,2,128,3,0,1,0,sales,low
14968,87518,2,128,3,0,1,0,sales,medium
14969,87520,2,157,3,0,1,0,sales,medium
14970,87530,4,225,5,0,1,0,sales,medium
14971,87533,2,140,3,0,1,0,sales,medium

# **total number of projects done by support dept**

In [175]:
dept = df.groupby('department')
supp = dept.get_group('support')
supp

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
46,1310,2,147,3,0,1,0,support,low
47,1311,3,273,6,0,1,0,support,low
48,1316,2,148,3,0,1,0,support,low
49,1319,2,147,3,0,1,0,support,low
50,10865,6,152,2,0,1,0,support,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [176]:
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

# **maximum number of projects done by sales dept**

In [178]:
dept = df.groupby('department')
sal = dept.get_group('sales')
sal['number_project'].max()

np.int64(7)

# **minimum number of projects done by IT dept**

In [179]:
dept=df.groupby('department')
IT=dept.get_group('IT')
IT["number_project"].min()

np.int64(2)

# **number of employess working in accountig dept**

In [180]:
dept=df.groupby('department')
acc=dept.get_group('accounting')
acc["employee_id"].count()

np.int64(767)

# **total spent in a company of employees**

# **5.Total time spent in a company of the employees who are all getting high salary**

In [181]:
sal=df.groupby("salary")
high=sal.get_group('high')
high['time_spend_company'].sum()

np.int64(4568)

# **6.Total time spent in a company of the employees who are all getting low salary**

In [182]:
sal=df.groupby("salary")
low=sal.get_group('low')
low['time_spend_company'].sum()

np.int64(25154)

# **7.Total number of work accidents in RandD dept**

In [183]:
dept=df.groupby("department")
rd=dept.get_group('RandD')
rd['Work_accident'].sum()

np.int64(134)

# **8.Avg monthly hrs spent by marketing dept**

In [184]:
dept=df.groupby("department")
mark=dept.get_group("marketing")
mark["average_montly_hours"].mean()

np.float64(199.3857808857809)

# **9.Total number of projects done by all dept**

In [185]:
dept=df.groupby("department")
dept["number_project"].sum()

department
IT              4683
RandD           3033
accounting      2934
hr              2701
management      2432
marketing       3164
product_mng     3434
sales          15634
support         8479
technical      10548
Name: number_project, dtype: int64

# **10.Total time spent in a company based on each and every salary**

In [186]:
sal=df.groupby('salary')
sal['time_spend_company'].sum()

salary
high       4568
low       25154
medium    22748
Name: time_spend_company, dtype: int64

# Concatation
**row wise concatation**

In [187]:
# sales_jan = pd.read_csv('data/Sales_jan')

In [188]:
# sales_feb=pd.read_csv("/content/Sales_Feb")
# sales_feb

In [189]:
# df=pd.concat([sales_jan,sales_feb])
# df

In [190]:
# df=pd.concat([sales_jan,sales_feb],ignore_index=True)
# df

**column wise concatation**

*#syntax

**pd.concat([df1,df2,...n],axis=1)**

In [191]:
# disc=pd.read_csv('/content/Discount')
# disc

In [ ]:
# df=pd.concat([sales_feb,disc],axis=1)
# df

# Inner join

**# syntax

**df=pd.merge(df1,df2,on='common_col',how='join_type')**

<!-- ord=pd.read_csv('/content/Orders')
ord -->

In [193]:
# ord=pd.read_csv('/content/Orders')
# ord

In [194]:
# pro=pd.read_csv('/content/Products')
# pro

<!-- pro=pd.read_csv('/content/Products')
pro -->

In [195]:
# pd.merge(ord,pro,on='product_id')

In [196]:
# pd.merge(ord,pro,on='product_id',how='inner')

**Left join**

In [ ]:
# pd.merge(ord,pro,on='product_id',how='left')
# pd.merge(pro,ord,on='product_id',how='left')

**Right Join**

In [198]:
# pd.merge(ord,pro,on='product_id',how='right')

**Outer join**

In [199]:
# pd.merge(ord,pro,on='product_id',how='outer')

# **feature engineering**

In [200]:
# df=pd.read_csv("/content/Orders dataset")
# df

In [201]:
# df['Revenue']=df['price']*df['quantity']
# df

In [202]:
# df['order_date'].dtype

In [203]:
# df["order_date"]=pd.to_datetime(df["order_date"])
# df.info()

In [204]:
# df["Month"]=df["order_date"].dt.month
# df

In [205]:
# df["Month_Name"]=df["order_date"].dt.month_name()
# df

In [206]:
# df["Day_Name"]=df["order_date"].dt.day_name()
# df

In [207]:
# df["Day"]=df["order_date"].dt.day
# df

In [208]:
# df["Year"]=df["order_date"].dt.year
# df

In [209]:
# df["Date"]=df["order_date"].dt.date
# df

In [ ]:
# 1.Which month has more number of sales?/Total revenue of each month?

# df.groupby("Month_Name")["Revenue"].sum()

# April is having more sales

# 2.Which day has more orders?

# df.groupby("Day_Name")["order_id"].count()

# Monday,Friday and Saturday is having more orders

# 3.Which year has maximum revenue?

# df.groupby("Year")["Revenue"].max()

# 2024 is having maximum revenue

# 4.Total quantity ordered in each date

# df.groupby("Date")["quantity"].sum()

# # Save as a csv flie

# #Syntax:
# #df.to_csv("Dataset name.csv",index=False)

# df.to_csv("Processed_Orders.csv")

# pd.read_csv("/content/Processed_Orders.csv")

# df

# df.to_csv("Cleaned_Orders.csv",index=False)

# pd.read_csv("/content/Cleaned_Orders.csv")

# Save data as excel file

# # Syntax:
# # df.to_excel("Dataset name.xlsx",index=False)

# df.to_excel("Orders_Excel.xlsx",index=False)

# pd.read_excel("/content/Orders_Excel.xlsx")