# Pandas

## **Series**


**pd.Series([val1,val2,val3...],name="seriesname",index=[index1,index2...])**

In [2]:
import pandas as pd

In [6]:
age = pd.Series([10,20,30],name="age")
print(age)
print("age at index 2: ",age[2])

0    10
1    20
2    30
Name: age, dtype: int64
age at index 2:  30

In [ ]:
print("age"[0])  # string accessing

a

In [7]:
marks = pd.Series([90,40,50,95],index=['Ganesh','suresh','ramesh','manish'])
print(marks)

Ganesh    90
suresh    40
ramesh    50
manish    95
dtype: int64

In [8]:
print(marks['manish'])

95

In [11]:
Score = pd.Series([90,40,50,95],name="marks", index=['Ganesh','suresh','ramesh','manish'])
print("Marks of ganesh: ",marks['Ganesh'])

Marks of ganesh:  90

# slicing on pandas

syntax

**var[starting_value:ending_value:updation]**

In [19]:
marks =pd.Series([110,120,130,140],name='Marks')
marks

0    110
1    120
2    130
3    140
Name: Marks, dtype: int64

In [20]:
print(marks[0:4])
print(marks[::2])
print(marks[1::2])
print(marks[2:8])

0    110
1    120
2    130
3    140
Name: Marks, dtype: int64
0    110
2    130
Name: Marks, dtype: int64
1    120
3    140
Name: Marks, dtype: int64
2    130
3    140
Name: Marks, dtype: int64

# filtering on series

syntax

**var[condition]**

In [21]:
sal=pd.Series([10000,35000,65000,55000,45000,40000],name='salary')
sal

0    10000
1    35000
2    65000
3    55000
4    45000
5    40000
Name: salary, dtype: int64

In [27]:
print(sal[sal<=50000])
print(sal[sal>10000])
print(sal[sal!=45000])

0    10000
1    35000
4    45000
5    40000
Name: salary, dtype: int64
1    35000
2    65000
3    55000
4    45000
5    40000
Name: salary, dtype: int64
0    10000
1    35000
2    65000
3    55000
5    40000
Name: salary, dtype: int64

# 2 rules for multiple conditions 

**1. () for each and every conditions**

**2.  & for and ,| for or**

In [29]:
sal

0    10000
1    35000
2    65000
3    55000
4    45000
5    40000
Name: salary, dtype: int64

In [30]:
print(sal[(sal>=55000) & (sal<=650000)])

2    65000
3    55000
Name: salary, dtype: int64

In [31]:
print(sal[(sal==55000) | (sal==65000)])

2    65000
3    55000
Name: salary, dtype: int64

# **DataFrame**

syntax

**variable_name={**

**"col_name1":[val1,val2,va3......],**

**"col_name2":[val1,val2,va3......],**

**"col_name3":[val1,val2,va3......],**

**"col_name4":[val1,val2,va3......],**

}**

**pd.DataFrame(variable)**

In [32]:
data={
    "name":['Revanth','Kumar','Bhanu'],
    "exp":[1,5,7],
    'salary':[100000,50000,800000]
}
df = pd.DataFrame(data)
df

      name  exp  salary
0  Revanth    1  100000
1    Kumar    5   50000
2    Bhanu    7  800000

In [36]:
print(df['name'])
df[df['salary']>50000]

0    Revanth
1      Kumar
2      Bhanu
Name: name, dtype: object

      name  exp  salary
0  Revanth    1  100000
2    Bhanu    7  800000

In [39]:
data={
    'movie_name':['winner','spidrman','kgf','salar'],
    'hero':['raj','kumar','ragu','ram'],
    'heroine':['has','kamala','charim','rashimika']
}
movies=pd.DataFrame(data)
print(movies)
print(movies[movies["hero"]=='ragu'])

  movie_name   hero    heroine
0     winner    raj        has
1   spidrman  kumar     kamala
2        kgf   ragu     charim
3      salar    ram  rashimika
  movie_name  hero heroine
2        kgf  ragu  charim

# operations on data frame

# indexing

# slicing

# filtering

# 1.indexing

**df[col_name][index]**

In [44]:
movies

  movie_name   hero    heroine
0     winner    raj        has
1   spidrman  kumar     kamala
2        kgf   ragu     charim
3      salar    ram  rashimika

In [54]:
movies["movie_name"]

0      winner
1    spidrman
2         kgf
3       salar
Name: movie_name, dtype: object

In [53]:
movies[["hero","heroine"]]

    hero    heroine
0    raj        has
1  kumar     kamala
2   ragu     charim
3    ram  rashimika

In [ ]:
movies["hero"][0] # indexing

'raj'

# **slicing on data frame**

**var[si:ei:up]**

In [49]:
df=pd.DataFrame({
    'products':['laptop','mouse','keybord','monitor','headphones'],
    'quantity':[1,5,3,2,8],
    'price':[65000,700,2500,35000,12000]
})
df

     products  quantity  price
0      laptop         1  65000
1       mouse         5    700
2     keybord         3   2500
3     monitor         2  35000
4  headphones         8  12000

In [50]:
print(df[::2])

     products  quantity  price
0      laptop         1  65000
2     keybord         3   2500
4  headphones         8  12000

In [51]:
print(df[1:4])

  products  quantity  price
1    mouse         5    700
2  keybord         3   2500
3  monitor         2  35000

In [52]:
print(df[::-1])

     products  quantity  price
4  headphones         8  12000
3     monitor         2  35000
2     keybord         3   2500
1       mouse         5    700
0      laptop         1  65000

# **loc**

syntax

**df.loc[si:ei:up,['col1',col2','col3'.....]]**

ending index is inclusive in loc




**loc is a Pandas label-based indexing method.**

**It is used to access rows and columns using their labels/names.**

syntax 2

**df.loc[row_label, column_label]**

In [55]:
df

     products  quantity  price
0      laptop         1  65000
1       mouse         5    700
2     keybord         3   2500
3     monitor         2  35000
4  headphones         8  12000

In [ ]:
print(df.loc[2]) #Select one row
print(df.loc[2, "quantity"]) #Select one column from a specific row
print(df.loc[:, ["quantity", "price"]]) #Select multiple columns
print(df.loc[[0, 2], ["quantity", "price"]]) #Select rows + columns
print(df.loc[df["quantity"] > 5]) #filtering with loc :========= df.loc[condition, columns]
print(df.loc[df["quantity"] > 5, ["products", "price"]]) #only particular columns
df.loc[4,"quantity"]=10  # modifying the data 
print(df.loc[4,"quantity"])
df.loc[df["quantity"] < 2, "quantity"] = 5 # modify multiple rows -- make quantity as 5 wher quantity less than 2

products    keybord
quantity          3
price          2500
Name: 2, dtype: object
3
   quantity  price
0         5  65000
1         5    700
2         3   2500
3         2  35000
4        10  12000
   quantity  price
0         5  65000
2         3   2500
     products  quantity  price
4  headphones        10  12000
     products  price
4  headphones  12000
10

     products  quantity  price
0      laptop         5  65000
1       mouse         5    700
2     keybord         3   2500
3     monitor         2  35000
4  headphones        10  12000

In [56]:
df.loc[0:1,['products','quantity']]

  products  quantity
0   laptop         1
1    mouse         5

# **iloc**

syntax

**variable_name.iloc[row_slice,col_slice]**

**iloc means integer-location based indexing.**

**It is used to access DataFrame data using integer positions.**

In [71]:
d={
    "movies_name":['toxic','mizapur','kgf','spiderman','kantara','ghilli'],
    'hero_names':['yash','kahlin bhaia','yash','tom holland','rishib shetty','vijay'],
    'heroine':['kiara','bhumi','srinihi','zendaya','sapthami','trisha'],
    "movies_name1":['toxic','mizapur','kgf','spiderman','kantara','ghilli'],
    'hero_names1':['yash','kahlin bhaia','yash','tom holland','rishib shetty','vijay'],
    'heroine1':['kiara','bhumi','srinihi','zendaya','sapthami','trisha'],
    "movies_name2":['toxic','mizapur','kgf','spiderman','kantara','ghilli'],
    'hero_names2':['yash','kahlin bhaia','yash','tom holland','rishib shetty','vijay'],
    'heroine2':['kiara','bhumi','srinihi','zendaya','sapthami','trisha']
}
movies=pd.DataFrame(d)
movies

,movies_name,hero_names,heroine,movies_name1,hero_names1,heroine1,movies_name2,hero_names2,heroine2
0,toxic,yash,kiara,toxic,yash,kiara,toxic,yash,kiara
1,mizapur,kahlin bhaia,bhumi,mizapur,kahlin bhaia,bhumi,mizapur,kahlin bhaia,bhumi
2,kgf,yash,srinihi,kgf,yash,srinihi,kgf,yash,srinihi
3,spiderman,tom holland,zendaya,spiderman,tom holland,zendaya,spiderman,tom holland,zendaya
4,kantara,rishib shetty,sapthami,kantara,rishib shetty,sapthami,kantara,rishib shetty,sapthami
5,ghilli,vijay,trisha,ghilli,vijay,trisha,ghilli,vijay,trisha

In [72]:
movies.iloc[0:4,0:6]

  movies_name    hero_names  heroine movies_name1   hero_names1 heroine1
0       toxic          yash    kiara        toxic          yash    kiara
1     mizapur  kahlin bhaia    bhumi      mizapur  kahlin bhaia    bhumi
2         kgf          yash  srinihi          kgf          yash  srinihi
3   spiderman   tom holland  zendaya    spiderman   tom holland  zendaya

In [73]:
movies.iloc[::2,::2]

  movies_name   heroine    hero_names1 movies_name2  heroine2
0       toxic     kiara           yash        toxic     kiara
2         kgf   srinihi           yash          kgf   srinihi
4     kantara  sapthami  rishib shetty      kantara  sapthami

In [90]:
print("=======select one row======")
print(movies.iloc[2]) 

print("=========one cell=========")
print(movies.iloc[2,0]) 

print("=========select multiple rows=========")
print(movies.iloc[[0,2]])

print("=============Select multiple columns=========")
print("============select all rows , only columns at 1 and 3=============")
print(movies.iloc[:,[1,3]])

print("=================select all rows , select columns from 1 to 3(columns 1 and 2)")
print(movies.iloc[:,1:3])

=======select one row======
movies_name         kgf
hero_names         yash
heroine         srinihi
movies_name1        kgf
hero_names1        yash
heroine1        srinihi
movies_name2        kgf
hero_names2        yash
heroine2        srinihi
Name: 2, dtype: object
=========one cell=========
kgf
=========select multiple rows=========
  movies_name hero_names  heroine movies_name1 hero_names1 heroine1  \
0       toxic       yash    kiara        toxic        yash    kiara
2         kgf       yash  srinihi          kgf        yash  srinihi

  movies_name2 hero_names2 heroine2
0        toxic        yash    kiara
2          kgf        yash  srinihi
=============Select multiple columns=========
============select all rows , only columns at 1 and 3=============
      hero_names movies_name1
0           yash        toxic
1   kahlin bhaia      mizapur
2           yash          kgf
3    tom holland    spiderman
4  rishib shetty      kantara
5          vijay       ghilli
=================select all rows , select columns from 1 to 3(columns 1 and 2)
      hero_names   heroine
0           yash     kiara
1   kahlin bhaia     bhumi
2           yash   srinihi
3    tom holland   zendaya
4  rishib shetty  sapthami
5          vijay    trisha

In [ ]:
print(movies.iloc[:,[1,3]])

print(movies.iloc[:,1:3])

      hero_names movies_name1
0           yash        toxic
1   kahlin bhaia      mizapur
2           yash          kgf
3    tom holland    spiderman
4  rishib shetty      kantara
5          vijay       ghilli

=================================================;t
      hero_names   heroine
0           yash     kiara
1   kahlin bhaia     bhumi
2           yash   srinihi
3    tom holland   zendaya
4  rishib shetty  sapthami
5          vijay    trisha

# filtering on data frame

syntax

**variable_name[condition]**

In [91]:
df=pd.DataFrame({
    'name':['ram','lilly','raj','sham','luca'],
    'disease':['fever','cancer','sugar','bp','covid'],
    'age':[25,56,76,45,23],
    "bill":[2000,100000,4000,3000,50000]

})

In [92]:
df

    name disease  age    bill
0    ram   fever   25    2000
1  lilly  cancer   56  100000
2    raj   sugar   76    4000
3   sham      bp   45    3000
4   luca   covid   23   50000

In [93]:
df[df["bill"]>4000]

    name disease  age    bill
1  lilly  cancer   56  100000
4   luca   covid   23   50000

In [94]:
df[df["age"]<50]

   name disease  age   bill
0   ram   fever   25   2000
3  sham      bp   45   3000
4  luca   covid   23  50000

In [96]:
df[df["disease"]=="cancer"]

    name disease  age    bill
1  lilly  cancer   56  100000

In [99]:
df[(df['age']>30) & (df['disease']=='sugar')]

  name disease  age  bill
2  raj   sugar   76  4000

# **to create series using numpy and pandas**

In [100]:

import numpy as np

In [101]:
emp_id=np.arange(101,201)
pd.Series(emp_id,name='employee_id')

0     101
1     102
2     103
3     104
4     105
     ...
95    196
96    197
97    198
98    199
99    200
Name: employee_id, Length: 100, dtype: int64

# **to create dataframe using numpy and pandas**

In [102]:
emp_id = np.arange(101,201)
sal =np.random.randint(20000,80000,100)
age=np.random.randint(21,51,100)
bonus = np.ones(100,dtype=int)
df = pd.DataFrame({
    'employee_id':emp_id,
    'salary':sal,
    'age':age,
    'bonus':bonus
})
df

    employee_id  salary  age  bonus
0           101   26436   45      1
1           102   23094   27      1
2           103   37007   31      1
3           104   75360   30      1
4           105   68507   39      1
..          ...     ...  ...    ...
95          196   45482   24      1
96          197   30170   37      1
97          198   71958   32      1
98          199   42876   40      1
99          200   27127   33      1

[100 rows x 4 columns]

# **Converting CSV,Excel,JSON into DataFrame**

In [1]:
# df=pd.read_csv('/content/flipkart_sales.csv')
# df

In [2]:
'''df=pd.read_excel('/content/population.xlsx')
df'''

"df=pd.read_excel('/content/population.xlsx')\ndf"

# **JSON**

In [5]:
import pandas as pd
data={
  "colors": [
    {"name": "Black", "hex": "#000000", "rgb": {"r": 0, "g": 0, "b": 0}, "category": "neutral"},
    {"name": "White", "hex": "#FFFFFF", "rgb": {"r": 255, "g": 255, "b": 255}, "category": "neutral"},
    {"name": "Red", "hex": "#FF0000", "rgb": {"r": 255, "g": 0, "b": 0}, "category": "primary"},
    {"name": "Green", "hex": "#00FF00", "rgb": {"r": 0, "g": 255, "b": 0}, "category": "primary"},
    {"name": "Blue", "hex": "#0000FF", "rgb": {"r": 0, "g": 0, "b": 255}, "category": "primary"},
    {"name": "Yellow", "hex": "#FFFF00", "rgb": {"r": 255, "g": 255, "b": 0}, "category": "secondary"},
    {"name": "Cyan", "hex": "#00FFFF", "rgb": {"r": 0, "g": 255, "b": 255}, "category": "secondary"},
    {"name": "Magenta", "hex": "#FF00FF", "rgb": {"r": 255, "g": 0, "b": 255}, "category": "secondary"},
    {"name": "Orange", "hex": "#FFA500", "rgb": {"r": 255, "g": 165, "b": 0}, "category": "warm"},
    {"name": "Pink", "hex": "#FFC0CB", "rgb": {"r": 255, "g": 192, "b": 203}, "category": "warm"},
    {"name": "Purple", "hex": "#800080", "rgb": {"r": 128, "g": 0, "b": 128}, "category": "cool"},
    {"name": "Violet", "hex": "#EE82EE", "rgb": {"r": 238, "g": 130, "b": 238}, "category": "cool"},
    {"name": "Brown", "hex": "#A52A2A", "rgb": {"r": 165, "g": 42, "b": 42}, "category": "earth"},
    {"name": "Maroon", "hex": "#800000", "rgb": {"r": 128, "g": 0, "b": 0}, "category": "earth"},
    {"name": "Olive", "hex": "#808000", "rgb": {"r": 128, "g": 128, "b": 0}, "category": "earth"},
    {"name": "Teal", "hex": "#008080", "rgb": {"r": 0, "g": 128, "b": 128}, "category": "cool"},
    {"name": "Navy", "hex": "#000080", "rgb": {"r": 0, "g": 0, "b": 128}, "category": "cool"},
    {"name": "Gray", "hex": "#808080", "rgb": {"r": 128, "g": 128, "b": 128}, "category": "neutral"},
    {"name": "Silver", "hex": "#C0C0C0", "rgb": {"r": 192, "g": 192, "b": 192}, "category": "neutral"},
    {"name": "Lime", "hex": "#32CD32", "rgb": {"r": 50, "g": 205, "b": 50}, "category": "nature"},
    {"name": "Aqua", "hex": "#00CED1", "rgb": {"r": 0, "g": 206, "b": 209}, "category": "nature"},
    {"name": "Coral", "hex": "#FF7F50", "rgb": {"r": 255, "g": 127, "b": 80}, "category": "warm"},
    {"name": "Salmon", "hex": "#FA8072", "rgb": {"r": 250, "g": 128, "b": 114}, "category": "warm"},
    {"name": "Khaki", "hex": "#F0E68C", "rgb": {"r": 240, "g": 230, "b": 140}, "category": "earth"},
    {"name": "Plum", "hex": "#DDA0DD", "rgb": {"r": 221, "g": 160, "b": 221}, "category": "cool"},
    {"name": "Gold", "hex": "#FFD700", "rgb": {"r": 255, "g": 215, "b": 0}, "category": "warm"},
    {"name": "Crimson", "hex": "#DC143C", "rgb": {"r": 220, "g": 20, "b": 60}, "category": "warm"},
    {"name": "Indigo", "hex": "#4B0082", "rgb": {"r": 75, "g": 0, "b": 130}, "category": "cool"},
    {"name": "Turquoise", "hex": "#40E0D0", "rgb": {"r": 64, "g": 224, "b": 208}, "category": "nature"},
    {"name": "Ivory", "hex": "#FFFFF0", "rgb": {"r": 255, "g": 255, "b": 240}, "category": "neutral"},
    {"name": "Beige", "hex": "#F5F5DC", "rgb": {"r": 245, "g": 245, "b": 220}, "category": "neutral"},
    {"name": "Lavender", "hex": "#E6E6FA", "rgb": {"r": 230, "g": 230, "b": 250}, "category": "cool"},
    {"name": "Mint", "hex": "#98FF98", "rgb": {"r": 152, "g": 255, "b": 152}, "category": "nature"},
    {"name": "Peach", "hex": "#FFCBA4", "rgb": {"r": 255, "g": 203, "b": 164}, "category": "warm"},
    {"name": "Slate", "hex": "#708090", "rgb": {"r": 112, "g": 128, "b": 144}, "category": "neutral"}
  ]
}
df=pd.json_normalize(data["colors"])

# **pandas built in methods to perform data exploration**

# **head()**

syntax

**variablename.head()**

**variablename.head(n)**

In [6]:
df.head()

    name      hex category  rgb.r  rgb.g  rgb.b
0  Black  #000000  neutral      0      0      0
1  White  #FFFFFF  neutral    255    255    255
2    Red  #FF0000  primary    255      0      0
3  Green  #00FF00  primary      0    255      0
4   Blue  #0000FF  primary      0      0    255

In [7]:
df.head(2)

    name      hex category  rgb.r  rgb.g  rgb.b
0  Black  #000000  neutral      0      0      0
1  White  #FFFFFF  neutral    255    255    255

# **tail()**


**variablename.tail()--->bottom 5 rows**


**variablename.tail(n)---> bottom n rows**

In [8]:
df.tail()

        name      hex category  rgb.r  rgb.g  rgb.b
30     Beige  #F5F5DC  neutral    245    245    220
31  Lavender  #E6E6FA     cool    230    230    250
32      Mint  #98FF98   nature    152    255    152
33     Peach  #FFCBA4     warm    255    203    164
34     Slate  #708090  neutral    112    128    144

In [9]:
df.tail(3)

     name      hex category  rgb.r  rgb.g  rgb.b
32   Mint  #98FF98   nature    152    255    152
33  Peach  #FFCBA4     warm    255    203    164
34  Slate  #708090  neutral    112    128    144

# **info()**

syntax

**variable_name.info()**

**used to understand the structure and quality of a dataset.**

shows information such as:
- Number of rows
- Number of columns
- Column names
- Non-null values
- Data types
- Memory usage

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      35 non-null     object
 1   hex       35 non-null     object
 2   category  35 non-null     object
 3   rgb.r     35 non-null     int64
 4   rgb.g     35 non-null     int64
 5   rgb.b     35 non-null     int64
dtypes: int64(3), object(3)
memory usage: 1.8+ KB

# **describe()**

**provides statistical summary information for numerical columns**

**works on numerical columns**

syntax

**variable_name.describe()-->numeric colum default**

**variabl_name.describe(include=object)-->for object val**

In [11]:
df.describe()

            rgb.r       rgb.g       rgb.b
count   35.000000   35.000000   35.000000
mean   157.600000  141.600000  131.114286
std    100.781126   97.005518   93.533816
min      0.000000    0.000000    0.000000
25%     69.500000   31.000000   46.000000
50%    192.000000  160.000000  130.000000
75%    255.000000  227.000000  214.500000
max    255.000000  255.000000  255.000000

In [13]:
df.head(3)

    name      hex category  rgb.r  rgb.g  rgb.b
0  Black  #000000  neutral      0      0      0
1  White  #FFFFFF  neutral    255    255    255
2    Red  #FF0000  primary    255      0      0

In [16]:
print("======summary of columns whose data type is object , doesn't include numerical columns======")
print(df.describe(include=object))

======summary of columns whose data type is object , doesn't include numerical columns======
         name      hex category
count      35       35       35
unique     35       35        7
top     Black  #000000  neutral
freq        1        1        7

In [21]:
print("++++========Include both NUMERICAL and CATEGORICAL/OBject  values===============")
print()
print(df.describe(include='all'))

++++========Include both NUMERICAL and CATEGORICAL/OBject  values===============

         name      hex category       rgb.r       rgb.g       rgb.b
count      35       35       35   35.000000   35.000000   35.000000
unique     35       35        7         NaN         NaN         NaN
top     Black  #000000  neutral         NaN         NaN         NaN
freq        1        1        7         NaN         NaN         NaN
mean      NaN      NaN      NaN  157.600000  141.600000  131.114286
std       NaN      NaN      NaN  100.781126   97.005518   93.533816
min       NaN      NaN      NaN    0.000000    0.000000    0.000000
25%       NaN      NaN      NaN   69.500000   31.000000   46.000000
50%       NaN      NaN      NaN  192.000000  160.000000  130.000000
75%       NaN      NaN      NaN  255.000000  227.000000  214.500000
max       NaN      NaN      NaN  255.000000  255.000000  255.000000

# **Column attribute**

syntax

**var.columns**

In [22]:
df.columns

Index(['name', 'hex', 'category', 'rgb.r', 'rgb.g', 'rgb.b'], dtype='object')

In [25]:
df["category"].dtype # pandas treat strings as objects

dtype('O')

In [26]:
df['name'].unique()

array(['Black', 'White', 'Red', 'Green', 'Blue', 'Yellow', 'Cyan',
       'Magenta', 'Orange', 'Pink', 'Purple', 'Violet', 'Brown', 'Maroon',
       'Olive', 'Teal', 'Navy', 'Gray', 'Silver', 'Lime', 'Aqua', 'Coral',
       'Salmon', 'Khaki', 'Plum', 'Gold', 'Crimson', 'Indigo',
       'Turquoise', 'Ivory', 'Beige', 'Lavender', 'Mint', 'Peach',
       'Slate'], dtype=object)